# PostgreSQL Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/chatsdb
spring.datasource.username=postgres
spring.datasource.password=123456

spring.security.user.name=admin
spring.security.user.password=admin123
# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Show SQL Queries
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update